### ISSUE TITLE
Support for vim8 lambda expressions

### ISSUE THREAD

**Issue by tomtom** [Kuniwak/vint#209]
Could you please add support for vim8 lambda expressions?

    {args -> expr}

Alternatively, is there a way to make vint skip certain lines entirely (so that it doesn't even try to parse them)?

Thanks!

**Comment by Kuniwak** [comment]
Thanks for reporting!
I'm glad because I'm an user of tcomment_vim :smile:

Currently, vim-vimlparser that Vint is using does not support lambda yet, so Vint cannot recognize it.

In the past, I have decided to use the external Vim script parser because I had no time to implement it. But now, vim-vimlparser is not actively maintained now.
So I'm awaiting to meet a Vim script parser actively maintained.

**Comment by blueyed** [comment]
Lambdas are handled by now.
